[package]
name = "dioxus_form"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "1.0", features = ["serde_derive"] }
dioxus = { version= "0.5", features=["web"]}
serde_json = "1.0"
